

const ActionType = {
    PLAY_PAUSE_CLICK: 'PLAY_PAUSE_CLICK',
    RESET_CLICK: 'RESET_CLICK',

    ALARM_CHANGED: 'ALARM_CHANGED',
    ALARM_VOL_CHANGED: 'ALARM_VOL_CHANGED',

    BREAK_LEN_CHANGED: 'BREAK_LEN_CHANGED',
    SESSION_LEN_CHANGED: 'SESSION_LEN_CHANGED',

    QUOTE_FETCHING: 'QUOTE_FETCHING',
    QUOTE_FETCHED: 'QUOTE_FETCHED',

    CHANGE_SESSION: 'CHANGE_SESSION',
    DECREMENT_TIME: 'DECREMENT_TIME'
}

export default ActionType;