

const ActionTypes = {
    TOOGLE_POWER: 'TOOGLE_POWER',
    CHG_VOLUME: 'CHANGE_VOLUME',
    CHG_BANK: 'CHANGE_BANK',
    DRUMPAD_PRESS: 'DRUMPAD_PRESS',
    TOGGLE_OVERLAY: 'TOOGLE_OVERLAY',
    SET_AUDIO: 'SET_AUDIO',
    PLAY_PAUSE: 'PLAY_PAUSE',
    RESET_AUDIO: 'RESET_AUDIO'
}

export default ActionTypes;